CP observable with the polarimetric vector
cms-tau-pog/TauMLTools pull request #120
Opened 2022-06-27 08:37 UTC by msessini

This pull request includes the computation of the CP observable PhiCP at generated level for hadronic tau decays with the polarimetric vector. A few more variables have been added to the output ntuple such as spin weights from Tauola's TauSpinner package, the PuppiMET and its covariance, the DeepMET and the generated MET.

2022-07-09 12:05 UTC, kandrosov requested changes

2022-07-09 12:05 UTC, kandrosov commented on env.sh
> +
undo modifications so that `env.sh` do not appear in the changed files list for this PR.

2022-07-11 12:27 UTC, msessini commented on Analysis/interface/CPfunctions.h
> +    }
Here I need the full tau momenta including neutrinos

2022-07-11 14:11 UTC, kandrosov requested changes

2022-07-11 14:11 UTC, kandrosov commented on Production/crab/configs/2016UL/tau_cp/Higgs.txt
> +GluGluHToTauTau_M125   /GluGluHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM
for 2016 there are two periods: preVFP and postVFP. Currently configs for preVFP samples are missing. E.g.
```
/GluGluHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2/MINIAODSIM
```

2022-07-12 08:18 UTC, kandrosov approved these changes

2022-07-12 08:19 UTC, merged