Added 2018UL configs
cms-tau-pog/TauMLTools pull request #150
Opened 2023-04-14 14:56 UTC by conformist89

2023-04-17 10:04 UTC, kandrosov requested changes
- update params to be aligned with the ones for Production
- add more Higgs samples (SM H, MSSM H, HH)
- data: I don't think we need DoubleMuon and JetHT -> remove them for now
- data: check if GT36 samples are available EGamma B&D, Tau A&D
- define overseer.cfg
- check that things run and add instructions to the readme

2023-05-25 09:52 UTC, conformist89 commented
> Looks good, thanks! Please add Z' and HH->bbtautau samples.

@kandrosov could you please remind me how to find Z` samples in DAS?

2023-05-25 10:03 UTC, conformist89 commented
There is one more thing: it works locally but if I try to test dryrun option I have the following error: CMSSW: ModuleNotFoundError: No module named 'TauMLTools.Production.sampleConfig'. It's weird because Production.py and sampleConfig.py are located in the same folder.

2023-05-26 13:19 UTC, shedprog commented
> > Looks good, thanks! Please add Z' and HH->bbtautau samples.
> 
> @kandrosov could you please remind me how to find Z` samples in DAS?

Unfortunately, from what I see, Zprime to TauTau/EE/MuMu is not available in UL 2018 setup: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FZprimeToTauTau*%2FRunIISummer20UL18MiniAOD*-106X_upgrade2018*%2FMINIAODSIM

2023-05-26 14:06 UTC, kandrosov commented
ok, indeed I also can't find Z' for UL... However I propose adding following samples. Mainly for for tau & di-tau reconstruction, but also useful for tau ID

 m(tautau) = 125 GeV, more jet activity:
```
/GluGluToHHTo2B2Tau_TuneCP5_PSWeights_node_SM_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/TTHHTo2B2Tau_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
```

m(tautau) = 125 GeV, more jet activity & bigger boost:
```
/GluGluToRadionToHHTo2B2Tau_M-250_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-260_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-270_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-280_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-300_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-320_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-350_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-400_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-450_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-500_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-550_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-600_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-650_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-700_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-750_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-800_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-850_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-900_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1000_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1100_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v4/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1250_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1300_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1400_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1500_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1600_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1700_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1750_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1800_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-1900_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v4/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-2000_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-2200_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-2400_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-2500_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-2600_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v4/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-2800_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM
/GluGluToRadionToHHTo2B2Tau_M-3000_TuneCP5_PSWeights_narrow_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
```

m(tautau) != 125 GeV. I didn't find MSSM H->tautau UL samples, but these ones should do:
```
/NMSSM_XToYHTo2Tau2B_MX-240_MY-60_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-240_MY-70_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-240_MY-80_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-240_MY-90_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-240_MY-100_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-280_MY-60_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-280_MY-70_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-280_MY-80_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-280_MY-90_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-280_MY-100_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
/NMSSM_XToYHTo2Tau2B_MX-280_MY-125_TuneCP5_ [...]

2023-05-30 08:23 UTC, kandrosov commented
> There is one more thing: it works locally but if I try to test dryrun option I have the following error: CMSSW: ModuleNotFoundError: No module named 'TauMLTools.Production.sampleConfig'. It's weird because Production.py and sampleConfig.py are located in the same folder.

Have you added `sampleConfig.py` to the list of files to transfer? You also need to use a relative import, because the location of the files will be different on the crab side.

2023-05-30 08:59 UTC, conformist89 commented
> > There is one more thing: it works locally but if I try to test dryrun option I have the following error: CMSSW: ModuleNotFoundError: No module named 'TauMLTools.Production.sampleConfig'. It's weird because Production.py and sampleConfig.py are located in the same folder.
> 


> Have you added `sampleConfig.py` to the list of files to transfer? You also need to use a relative import, because the location of the files will be different on the crab side.

Yes, I added `sampleConfig.py` to the transfer list.

2023-05-30 09:17 UTC, kandrosov commented on Production/crab/configs/2018UL/Higgs.txt
> +VBFHToTauTau_M125    /VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
why Higgs is in txt format?

2023-05-30 09:21 UTC, kandrosov commented
> And I also set relative path to `Production.py` but I still face the problem with `sampleConfig.py` import

how do you import sampleConfig in Production.py? `from .sampleConfig import ...`?

2023-05-30 09:27 UTC, conformist89 commented on Production/crab/configs/2018UL/Higgs.txt
> +VBFHToTauTau_M125    /VBFHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM
Just fixed that

2023-05-30 09:28 UTC, conformist89 commented
> how do you import sampleConfig in Production.py? `from .sampleConfig import ...`?

`import TauMLTools.Production.sampleConfig as sampleConfig `

2023-05-30 10:02 UTC, kandrosov commented
> > how do you import sampleConfig in Production.py? `from .sampleConfig import ...`?
> 
> `import TauMLTools.Production.sampleConfig as sampleConfig `

you need to use a relative import. If it doesn't work, import the module by file name.

2023-05-30 12:07 UTC, kandrosov commented
> I also fixed relative import but now I have error : File "Production/python/Production.py" could not be opened! Isn't it the right way to set the way to the config, is it ?

Crab doesn't preserve directory structure for transfered files, so `cmsRunCfg` should be `Production.py` in the crabOverseer configs.

2023-05-30 12:24 UTC, conformist89 commented
> > I also fixed relative import but now I have error : File "Production/python/Production.py" could not be opened! Isn't it the right way to set the way to the config, is it ?
> 
> Crab doesn't preserve directory structure for transfered files, so `cmsRunCfg` should be `Production.py` in the crabOverseer configs.

Indeed, one should use relative path to `Production.py` (fixed above) but I can't execute dryrun due to the following error:   File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/submit.py", line 446, in executeTestRun
    events += (maxSeconds / float(report['cpu']['AvgEventTime']))
KeyError: 'AvgEventTime

2023-05-30 12:55 UTC, kandrosov commented
> I can't execute dryrun due to the following error: File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/submit.py", line 446, in executeTestRun events += (maxSeconds / float(report['cpu']['AvgEventTime'])) KeyError: 'AvgEventTime

indeed, for a dryrun crab expects some additional process customisation:
https://github.com/cms-tau-pog/TauMLTools/blob/c6085624bad58c5b390da2e6f4ef6abcc144f0ec/Production/crab/crab_test_HLT.yaml#L7

2023-05-30 13:25 UTC, conformist89 commented
> > I can't execute dryrun due to the following error: File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/submit.py", line 446, in executeTestRun events += (maxSeconds / float(report['cpu']['AvgEventTime'])) KeyError: 'AvgEventTime
> 
> indeed, for a dryrun crab expects some additional process customisation:
> 
> https://github.com/cms-tau-pog/TauMLTools/blob/c6085624bad58c5b390da2e6f4ef6abcc144f0ec/Production/crab/crab_test_HLT.yaml#L7

I added the line above but still have this error

2023-05-31 13:46 UTC, kandrosov commented on Production/crab/crab_test_tupleProd.yaml
> +    cmsRunOptions: "sampleType=MC,era=Run2_2018"
you need to update params in all configs:
- add `cmsRunOptions `
- remove sampleType, era, storeFailed

2023-05-31 13:48 UTC, kandrosov commented on Production/crab/crab_test_tupleProd.yaml
> +    cmsRunCfg: Production.py
`cmsRunCfg` should be defined in `overseer_cfg_tupleProd.yaml`, not here.

2023-06-01 08:16 UTC, kandrosov requested changes

2023-06-01 08:16 UTC, kandrosov commented on Production/crab/configs/2018UL/data.yaml
> +    cmsRunOptions: "sampleType=MC,era=Run2_2018"
sampleType=data

2023-06-01 13:36 UTC, kandrosov approved these changes

2023-06-02 12:22 UTC, kandrosov approved these changes

2023-06-08 09:56 UTC, merged