Full CNN architecture adaptation, and update of the DataLoader
cms-tau-pog/TauMLTools pull request #48
Opened 2021-06-25 08:44 UTC by shedprog

In the following PR working example of CNN with a queue-to-queue multiprocessing dataloader is introduced:

Currently, updated:
- [x] 2017v2/Training_p6.py with some modifications cloned to 2018v1/Training_v0p1.py
- [x] Adapted NN config variables (moved initialization from command.py to DataLoadet.get_config())
- [x] Added queue-to-queue multiprocessing, when one instance of c++ DataLoader is considered as a single-core worker

Todo checklist:
- [ ] Merge with changes in scaling and weighting
- [ ] Perform preliminary training with ~100k steps
- [ ] I/O performance optimization and profiling

Technical details and benchmarks:
(The tests were performed at the GPU model: NVIDIA GeForce GTX 1080 Ti computeCapability: 6.1, global device memory was limited to 10 Gb.)
- The runtime profiling of the step gives the results:
![image](https://user-images.githubusercontent.com/31743376/123395528-966ad700-d5a0-11eb-971e-aa0fb45405c0.png)
**Average Step Time (sum): 684.7 ms**
All Others Time (including I/O ops): 122.0 ms
Kernel Launch Time: 64.6 ms
Host Compute Time:7.9 ms
Device Compute Time: 490.1 ms

- At the moment, I do not observe significant increase of host memory during training, but to be checked on the bigger scale. Current plot is done for ~ 1000 batches, 500 taus each, 10 elements in queue,  5 dataloader workers
![image](https://user-images.githubusercontent.com/31743376/123396796-062d9180-d5a2-11eb-8d54-66a0213a6076.png)

2021-06-30 09:13 UTC, kandrosov commented on Training/python/DataLoader.py
> +    def ListToVector(l, elem_type):
`ListToVector` is a general purpose function, move its definition outside of DataLoader

2021-06-30 09:13 UTC, kandrosov commented on Training/python/DataLoader.py
> +            while True:
```python
while finish_counter < self.n_load_workers:
```

2021-07-22 09:00 UTC, kandrosov requested changes

2021-07-22 09:25 UTC, kandrosov commented on Training/python/DataLoader.py
> +    while batch_counter.value < n_batches or n_batches == -1:
it was a bug in the proposed `QueueEx.put` implementation. Here is the corrected version:
```python
    def put(self, item, retry_interval=0.3):
        while True:
            with self.n_puts.get_lock():
                if self.n_puts.value >= self.max_n_puts:
                    return False
                try:
                    self.mp_queue.put(item, False)
                    self.n_puts.value += 1
                    return True
                except FullException:
                    pass
            time.sleep(retry_interval)

```

2021-07-26 22:55 UTC, shedprog commented on Training/interface/DataLoader_main.h
> +    Data LoadData() {
I found the following options:
```c++
std::unique_ptr<Data> LoadData() {
...
return std::move(data);
}
``` 
or
```c++
Data* LoadData() {
...
return std::move(data.get());
}

2021-07-29 22:19 UTC, shedprog commented
After final modification, few more benchmarks were done:

Training is run with 13GB GPU available on NVIDIA Tesla P100-PCIE-16GB
with `n_batches=1000, n_batches_val=200, max_queue_size=10, n_load_workers=4` epochwise the training looks stable (looking at general loss function)
![image](https://user-images.githubusercontent.com/31743376/127571973-ebeacb83-c503-4222-8257-265b0d358546.png)
the RAM consumption in the order of 12GB so, if it is run within htcondor job I would require ~15 GB

The profiling shows the following results (they are worst comparing to what was measured before, there are some peaks during which for some reasons dataloader does not response):
Average Step Time: 862.1 ms
All Others Time: 240.4 ms
Input Time: 148.9 ms
Kernel Launch Time: 59.9 ms
Device Compute Time: 400.3 ms
![image](https://user-images.githubusercontent.com/31743376/127572417-8d6d90ff-ff51-4ac6-916f-a89427330076.png)

2021-07-30 19:08 UTC, shedprog commented
I also implemented an alternative python dataloader-wrapper implementation https://github.com/shedprog/TauMLTools_newloader/blob/master/python/DataLoaderInter.py which is based on  tf.dataset.interleave functional:
https://github.com/shedprog/TauMLTools_newloader/blob/c6e44af77165806ddbfe6c58717c833584445385/python/DataLoaderInter.py#L231-L249 

So far, this implementation does not outperform mp.Queue-based that we have under the current master branch.

2021-08-01 09:35 UTC, kandrosov approved these changes

2021-08-01 09:40 UTC, kandrosov commented
I propose that we keep tuning of `tf.dataset.interleave` based implementation for future iterations. I'm going to merge this PR. Thank you!

2021-08-01 09:41 UTC, merged